development:
  adapter: postgresql
  database: bard_development
  username: root
  password: Kalosha
test:
  adapter: postgresql
  database: bard_test
  username: root
  password: Kalosha
production:
  adapter: postgresql
  database: bard
  username: root
  password: Kalosha
